In [ ]:
# from datasets import load_dataset
# ds = load_dataset("Bose345/sp500_earnings_transcripts") # original dataset: kurry/sp500_earnings_transcripts
# data = ds["train"]
# df = data.to_pandas()
# df.to_csv('earnings_transcripts.csv', index=False)

In [1]:
import pandas as pd
from datetime import timedelta
import yfinance as yf

In [2]:
df = pd.read_csv("earnings_transcripts.csv")

In [3]:
df.head()

,symbol,quarter,year,date,content,structured_content,company_name,company_id
0,A,4,2020,2020-11-23 16:30:00,"Operator: Good afternoon, and welcome to the A...","[{'speaker': 'Operator', 'text': ""Good afterno...","Agilent Technologies, Inc.",154924.0
1,A,3,2020,2020-08-18 16:30:00,"Operator: Good afternoon, and welcome to the A...","[{'speaker': 'Operator', 'text': ""Good afterno...","Agilent Technologies, Inc.",154924.0
2,A,2,2020,2020-05-21 16:30:00,"Operator: Good afternoon, and welcome to the A...","[{'speaker': 'Operator', 'text': ""Good afterno...","Agilent Technologies, Inc.",154924.0
3,A,1,2020,2020-02-18 16:30:00,Operator: Good afternoon and welcome to the Ag...,"[{'speaker': 'Operator', 'text': ""Good afterno...","Agilent Technologies, Inc.",154924.0
4,A,4,2021,2021-11-22 16:30:00,Operator: Good afternoon and welcome to the Ag...,"[{'speaker': 'Operator', 'text': ""Good afterno...","Agilent Technologies, Inc.",154924.0

In [7]:
print(df["date"].dtype)

str

In [9]:
df["date"] = pd.to_datetime(df["date"])
df = df.reset_index(drop=True)
df["event_id"] = df.index

print(df[["event_id", "symbol", "date"]].head())
print(df["date"].dtype)
print(df.columns)

   event_id symbol                date
0         0      A 2020-11-23 16:30:00
1         1      A 2020-08-18 16:30:00
2         2      A 2020-05-21 16:30:00
3         3      A 2020-02-18 16:30:00
4         4      A 2021-11-22 16:30:00
datetime64[us]
Index(['symbol', 'quarter', 'year', 'date', 'content', 'structured_content',
       'company_name', 'company_id', 'event_id'],
      dtype='str')

def get_event_market_data(
    symbol,
    date
):
    
    start = pd.Timestamp(date) - pd.Timedelta(days=60)
    end = pd.Timestamp(date) + pd.Timedelta(days=15)

    try:
        stock = yf.download(
            symbol,
            start=start,
            end=end,
            interval="1d",
            auto_adjust=True,
            progress=False,
            threads=False
        )
    except Exception:
        return None

    # In case that yfinance returns nothing
    if stock.empty:
        return None
    
    # Handle yfinance MultiIndex columns
    if isinstance(stock.columns, pd.MultiIndex):
        stock.columns = stock.columns.get_level_values(0)
    # Remove rows without a closing price
    stock = stock.dropna(subset=["Close"])

    if stock.empty:
        return None

    return stock

stock = get_event_market_data(
    "AAPL",
    "2020-10-29 17:00:00"
)

print(stock.head(3))
stock.shape

In [13]:
def get_stock_data(
    symbol,
    start_date,
    end_date
):
    
    try:
        stock = yf.download(
            symbol,
            start=start_date,
            end=end_date,
            interval="1d",
            auto_adjust=True,
            progress=False,
            threads=False
        )
    except Exception:
        return None

    # In case yfinance has no data
    if stock.empty:
        return None

    # Handle yfinance MultiIndex columns
    if isinstance(stock.columns, pd.MultiIndex):
        stock.columns = stock.columns.get_level_values(0)
    # Remove rows without a closing price
    stock = stock.dropna(subset=["Close"])
    if stock.empty:
        return None

    # Normalize and sort dates once
    stock.index = pd.to_datetime(stock.index).normalize()
    stock = stock.sort_index()

    return stock

In [14]:
# Store downloaded market data
market_data = {}

# Store tickers for which yfinance failed
failed_symbols = []

for symbol, group in df.groupby("symbol"):

    # Earliest and latest earnings dates for this company
    min_date = group["date"].min()
    max_date = group["date"].max()
    start_date = min_date - pd.Timedelta(days=60)
    end_date = max_date + pd.Timedelta(days=15)

    stock = get_stock_data(
        symbol,
        start_date,
        end_date
    )

    if stock is None:
        failed_symbols.append(symbol)
        continue

    market_data[symbol] = stock

$ABMD: possibly delisted; no timezone found

1 Failed download:
['ABMD']: possibly delisted; no timezone found
$ADCT: Data doesn't exist for startDate = 1136152800, endDate = 1198879200

1 Failed download:
['ADCT']: Data doesn't exist for startDate = 1136152800, endDate = 1198879200
$ADS: possibly delisted; no timezone found

1 Failed download:
['ADS']: possibly delisted; no timezone found
$ADT: Data doesn't exist for startDate = 1362231000, endDate = 1455715800

1 Failed download:
['ADT']: Data doesn't exist for startDate = 1362231000, endDate = 1455715800
$AKS: possibly delisted; no timezone found

1 Failed download:
['AKS']: possibly delisted; no timezone found
$ALTR: possibly delisted; no timezone found

1 Failed download:
['ALTR']: possibly delisted; no timezone found
$ALXN: possibly delisted; no timezone found

1 Failed download:
['ALXN']: possibly delisted; no timezone found
$AMBC: possibly delisted; no timezone found

1 Failed download:
['AMBC']: possibly delisted; no timezone found
$ANSS: possibly delisted; no timezone found

1 Failed download:
['ANSS']: possibly delisted; no timezone found
$AT: Data doesn't exist for startDate = 1132783200, endDate = 1194386400

1 Failed download:
['AT']: Data doesn't exist for startDate = 1132783200, endDate = 1194386400
$ATGE: possibly delisted; no timezone found

1 Failed download:
['ATGE']: possibly delisted; no timezone found
$ATVI: possibly delisted; no timezone found

1 Failed download:
['ATVI']: possibly delisted; no timezone found
$AVB: Data doesn't exist for startDate = 1197223200, endDate = 1747414800

1 Failed download:
['AVB']: Data doesn't exist for startDate = 1197223200, endDate = 1747414800
$BBBY: Data doesn't exist for startDate = 1139176800, endDate = 1524862800

1 Failed download:
['BBBY']: Data doesn't exist for startDate = 1139176800, endDate = 1524862800
$BEAM: Data doesn't exist for startDate = 1188248400, endDate = 1384552800

1 Failed download:
['BEAM']: Data doesn't exist for startDate = 1188248400, endDate = 1384552800
$BF.B: possibly delisted; no price data found  (1d 2008-01-03 10:00:00 -> 2025-03-20 10:00:00)

1 Failed download:
['BF.B']: possibly delisted; no price data found  (1d 2008-01-03 10:00:00 -> 2025-03-20 10:00:00)
$BIG: possibly delisted; no timezone found

1 Failed download:
['BIG']: possibly delisted; no timezone found
$BK: possibly delisted; no timezone found

1 Failed download:
['BK']: possibly delisted; no timezone found
$BTU: Data doesn't exist for startDate = 1189177200, endDate = 1423670400

1 Failed download:
['BTU']: Data doesn't exist for startDate = 1189177200, endDate = 1423670400
$CBH: possibly delisted; no timezone found

1 Failed download:
['CBH']: possibly delisted; no timezone found
$CERN: possibly delisted; no timezone found

1 Failed download:
['CERN']: possibly delisted; no timezone found
$CHIR: Data doesn't exist for startDate = 1128114000, endDate = 1140300000

1 Failed download:
['CHIR']: Data doesn't exist for startDate = 1128114000, endDate = 1140300000
$CIT: possibly delisted; no timezone found

1 Failed download:
['CIT']: possibly delisted; no timezone found
$CMA: possibly delisted; no timezone found

1 Failed download:
['CMA']: possibly delisted; no timezone found
$COOP: possibly delisted; no timezone found

1 Failed download:
['COOP']: possibly delisted; no timezone found
$CTLT: possibly delisted; no timezone found

1 Failed download:
['CTLT']: possibly delisted; no timezone found
$CTRA: possibly delisted; no timezone found

1 Failed download:
['CTRA']: possibly delisted; no timezone found
$CXO: possibly delisted; no timezone found

1 Failed download:
['CXO']: possibly delisted; no timezone found
$DAY: possibly delisted; no timezone found

1 Failed download:
['DAY']: possibly delisted; no timezone found
$DFS: possibly delisted; no timezone found

1 Failed download:
['DFS']: possibly delisted; no timezone found
$DISCK: possibly delisted; no timezone found

1 Failed download:
['DISCK']: possibly delisted; no timezone found
$DISH: possibly delisted; no timezone found

1 Failed download:
['DISH']: possibly delisted; no timezone found
$DNB: possibly delisted; no timezone found

1 Failed download:
['DNB']: possibly delisted; no timezone found
$DO: possibly delisted; no timezone found

1 Failed download:
['DO']: possibly delisted; no timezone found
$DRE: possibly delisted; no timezone found

1 Failed download:
['DRE']: possibly delisted; no timezone found
$DYN: Data doesn't exist for startDate = 1189371600, endDate = 1268686800

1 Failed download:
['DYN']: Data doesn't exist for startDate = 1189371600, endDate = 1268686800
$EA: Data doesn't exist for startDate = 1126990800, endDate = 1747869240

1 Failed download:
['EA']: Data doesn't exist for startDate = 1126990800, endDate = 1747869240
$ENDP: possibly delisted; no timezone found

1 Failed download:
['ENDP']: possibly delisted; no timezone found
$EQ: Data doesn't exist for startDate = 1180386000, endDate = 1243026000

1 Failed download:
['EQ']: Data doesn't exist for startDate = 1180386000, endDate = 1243026000
$EQR: Data doesn't exist for startDate = 1188658800, endDate = 1747321200

1 Failed download:
['EQR']: Data doesn't exist for startDate = 1188658800, endDate = 1747321200
$ETFC: possibly delisted; no timezone found

1 Failed download:
['ETFC']: possibly delisted; no timezone found
$FI: possibly delisted; no timezone found

1 Failed download:
['FI']: possibly delisted; no timezone found
$FL: possibly delisted; no timezone found

1 Failed download:
['FL']: possibly delisted; no timezone found
$FLIR: possibly delisted; no timezone found

1 Failed download:
['FLIR']: possibly delisted; no timezone found
$FRC: possibly delisted; no timezone found

1 Failed download:
['FRC']: possibly delisted; no timezone found
$HBI: possibly delisted; no timezone found

1 Failed download:
['HBI']: possibly delisted; no timezone found
$HES: possibly delisted; no timezone found

1 Failed download:
['HES']: possibly delisted; no timezone found
$HFC: possibly delisted; no timezone found

1 Failed download:
['HFC']: possibly delisted; no timezone found
$HOLX: possibly delisted; no timezone found

1 Failed download:
['HOLX']: possibly delisted; no timezone found
$IAC: possibly delisted; no timezone found

1 Failed download:
['IAC']: possibly delisted; no timezone found
$IGT: possibly delisted; no timezone found

1 Failed download:
['IGT']: possibly delisted; no timezone found
$INFO: Data doesn't exist for startDate = 1485554400, endDate = 1634141288

1 Failed download:
['INFO']: Data doesn't exist for startDate = 1485554400, endDate = 1634141288
$IPG: possibly delisted; no timezone found

1 Failed download:
['IPG']: possibly delisted; no timezone found
$JNPR: possibly delisted; no timezone found

1 Failed download:
['JNPR']: possibly delisted; no timezone found
$JWN: possibly delisted; no timezone found

1 Failed download:
['JWN']: possibly delisted; no timezone found
$K: possibly delisted; no timezone found

1 Failed download:
['K']: possibly delisted; no timezone found
$KODK: Data doesn't exist for startDate = 1133543700, endDate = 1297353600

1 Failed download:
['KODK']: Data doesn't exist for startDate = 1133543700, endDate = 1297353600
$KSU: possibly delisted; no timezone found

1 Failed download:
['KSU']: possibly delisted; no timezone found
$LEG: Data doesn't exist for startDate = 1179752400, endDate = 1645623000

1 Failed download:
['LEG']: Data doesn't exist for startDate = 1179752400, endDate = 1645623000
$LIFE: Data doesn't exist for startDate = 1235858400, endDate = 1361397600

1 Failed download:
['LIFE']: Data doesn't exist for startDate = 1235858400, endDate = 1361397600
$LM: possibly delisted; no timezone found

1 Failed download:
['LM']: possibly delisted; no timezone found
$LSI: possibly delisted; no timezone found

1 Failed download:
['LSI']: possibly delisted; no timezone found
$MDP: possibly delisted; no timezone found

1 Failed download:
['MDP']: possibly delisted; no timezone found
$MMC: possibly delisted; no timezone found

1 Failed download:
['MMC']: possibly delisted; no timezone found
$MNK: possibly delisted; no timezone found

1 Failed download:
['MNK']: possibly delisted; no timezone found
$MRO: possibly delisted; no timezone found

1 Failed download:
['MRO']: possibly delisted; no timezone found
$MXIM: possibly delisted; no timezone found

1 Failed download:
['MXIM']: possibly delisted; no timezone found
$NBL: possibly delisted; no timezone found

1 Failed download:
['NBL']: possibly delisted; no timezone found
$NE: Data doesn't exist for startDate = 1179684000, endDate = 1455890400

1 Failed download:
['NE']: Data doesn't exist for startDate = 1179684000, endDate = 1455890400
$NLSN: possibly delisted; no timezone found

1 Failed download:
['NLSN']: possibly delisted; no timezone found
$ODP: possibly delisted; no timezone found

1 Failed download:
['ODP']: possibly delisted; no timezone found
$PBCT: possibly delisted; no timezone found

1 Failed download:
['PBCT']: possibly delisted; no timezone found
$PD: Data doesn't exist for startDate = 1164924000, endDate = 1171404000

1 Failed download:
['PD']: Data doesn't exist for startDate = 1164924000, endDate = 1171404000
$PDCO: possibly delisted; no timezone found

1 Failed download:
['PDCO']: possibly delisted; no timezone found
$PLL: possibly delisted; no timezone found

1 Failed download:
['PLL']: possibly delisted; no timezone found
$POM: Data doesn't exist for startDate = 1172329200, endDate = 1487865600

1 Failed download:
['POM']: Data doesn't exist for startDate = 1172329200, endDate = 1487865600
$PXD: possibly delisted; no timezone found

1 Failed download:
['PXD']: possibly delisted; no timezone found
$QEP: possibly delisted; no timezone found

1 Failed download:
['QEP']: possibly delisted; no timezone found
$RRD: possibly delisted; no timezone found

1 Failed download:
['RRD']: possibly delisted; no timezone found
$SAF: Data doesn't exist for startDate = 1203285600, endDate = 1212613200

1 Failed download:
['SAF']: Data doesn't exist for startDate = 1203285600, endDate = 1212613200
$SBNY: Data doesn't exist for startDate = 1613833200, endDate = 1675256400

1 Failed download:
['SBNY']: Data doesn't exist for startDate = 1613833200, endDate = 1675256400
$SEE: possibly delisted; no timezone found

1 Failed download:
['SEE']: possibly delisted; no timezone found
$SIVB: possibly delisted; no timezone found

1 Failed download:
['SIVB']: possibly delisted; no timezone found
$SNV: possibly delisted; no timezone found

1 Failed download:
['SNV']: possibly delisted; no timezone found
$SRCL: possibly delisted; no timezone found

1 Failed download:
['SRCL']: possibly delisted; no timezone found
$STI: Data doesn't exist for startDate = 1179662400, endDate = 1572616800

1 Failed download:
['STI']: Data doesn't exist for startDate = 1179662400, endDate = 1572616800
$TGNA: possibly delisted; no timezone found

1 Failed download:
['TGNA']: possibly delisted; no timezone found
$TIF: possibly delisted; no timezone found

1 Failed download:
['TIF']: possibly delisted; no timezone found
$TSS: possibly delisted; no timezone found

1 Failed download:
['TSS']: possibly delisted; no timezone found
$TWTR: possibly delisted; no timezone found

1 Failed download:
['TWTR']: possibly delisted; no timezone found
$UST: Data doesn't exist for startDate = 1180270800, endDate = 1226152800

1 Failed download:
['UST']: Data doesn't exist for startDate = 1180270800, endDate = 1226152800
$VAL: Data doesn't exist for startDate = 1180105200, endDate = 1489590000

1 Failed download:
['VAL']: Data doesn't exist for startDate = 1180105200, endDate = 1489590000
$VAR: possibly delisted; no timezone found

1 Failed download:
['VAR']: possibly delisted; no timezone found
$VIAB: possibly delisted; no timezone found

1 Failed download:
['VIAB']: possibly delisted; no timezone found
$WBA: possibly delisted; no timezone found

1 Failed download:
['WBA']: possibly delisted; no timezone found
$WCG: possibly delisted; no timezone found

1 Failed download:
['WCG']: possibly delisted; no timezone found
$WPX: possibly delisted; no timezone found

1 Failed download:
['WPX']: possibly delisted; no timezone found
$WRK: possibly delisted; no timezone found

1 Failed download:
['WRK']: possibly delisted; no timezone found
$WYND: possibly delisted; no timezone found

1 Failed download:
['WYND']: possibly delisted; no timezone found
$X: possibly delisted; no timezone found

1 Failed download:
['X']: possibly delisted; no timezone found
$XEC: possibly delisted; no timezone found

1 Failed download:
['XEC']: possibly delisted; no timezone found
$XLNX: possibly delisted; no timezone found

1 Failed download:
['XLNX']: possibly delisted; no timezone found

In [24]:
len(failed_symbols), len(market_data), df.groupby("symbol").size().shape[0]

(102, 583, 685)

In [16]:
market_data["AAPL"]

Price            Close        High         Low        Open      Volume
Date
2005-08-15    1.426091    1.445532    1.389303    1.390199  1086727600
2005-08-16    1.383321    1.420708    1.382124    1.417417   537622400
2005-08-17    1.410240    1.418913    1.386909    1.387807   499724400
2005-08-18    1.384816    1.405753    1.368367    1.403061   442559600
2005-08-19    1.370758    1.396779    1.368964    1.384217   376569200
...                ...         ...         ...         ...         ...
2025-05-12  209.776123  210.253825  205.755562  209.955265    63775800
2025-05-13  211.905838  212.373579  207.994748  209.417863    51909300
2025-05-14  211.308716  212.910972  209.567133  211.408226    49325800
2025-05-15  210.432953  211.935700  208.532136  209.935358    45029500
2025-05-16  210.243881  211.547593  208.761058  211.338597    54737900

[4971 rows x 5 columns]

In [17]:
def build_event_window(
    stock,
    date,
    pre_days=30,
    post_days=7
):

    stock = stock.copy()

    # Normalize the index column of stock data from yfinance, i.e. market-data dates
    stock.index = pd.to_datetime(stock.index).normalize()
    stock = stock.sort_index()

    event_timestamp = pd.Timestamp(date)
    event_date = event_timestamp.normalize()

    # Compare market closing time to the event time on the event day
    market_close = event_date + pd.Timedelta(hours=16)
    after_close = event_timestamp >= market_close


    # Before-event
    if after_close:
        # The closing price on event_date is considered as pre-event data
        pre = stock[stock.index <= event_date].tail(pre_days)

    else:
        # The closing price on event_date is NOT pre-event information
        pre = stock[stock.index < event_date].tail(pre_days)

    # After-event
    if after_close:
        # First reaction is next trading day
        post = stock[stock.index > event_date].head(post_days)

    else:
        # Event-day close captures the initial reaction
        post = stock[stock.index >= event_date].head(post_days + 1)

    if len(pre) < pre_days:
        return None

    if after_close:
        if len(post) < post_days:
            return None
    else:
        if len(post) < post_days + 1:
            return None

    # Relative trading-day labels
    if after_close:
        pre["relative_day"] = range(-(pre_days - 1), 1)
        post["relative_day"] = range(1, post_days + 1)

    else:
        pre["relative_day"] = range(-pre_days, 0)
        post["relative_day"] = range(0, post_days + 1)

    pre["window"] = "pre"
    post["window"] = "post"

    return pd.concat([pre, post])

In [20]:
market_events = []
valid_events = []
failed_events = []

for _, event in df.iterrows():

    symbol = event["symbol"]
    date = event["date"]

    # Get already-downloaded market data
    stock = market_data.get(symbol)

    # Yahoo had no data for this ticker
    if stock is None:
        failed_events.append(event["event_id"])
        continue

    # Build the event window locally
    window = build_event_window(
        stock,
        date
    )

    # Not enough trading history
    if window is None:
        failed_events.append(event["event_id"])
        continue

    window["event_id"] = event["event_id"]
    window["symbol"] = symbol
    window["earnings_timestamp"] = date
    market_events.append(window)

    valid_events.append(event["event_id"])

In [22]:
len(market_events), len(valid_events), len(failed_events)

(29574, 29574, 3788)

In [25]:
market_events[0]

Price,Close,High,Low,Open,Volume,relative_day,window,event_id,symbol,earnings_timestamp
Date,,,,,,,,,,
2020-10-13,101.290070,101.856960,100.848091,101.309290,915500,-29,pre,0,A,2020-11-23 16:30:00
2020-10-14,100.944153,102.491080,100.809638,101.357307,906700,-28,pre,0,A,2020-11-23 16:30:00
2020-10-15,101.193970,101.578301,99.810381,100.021763,723000,-27,pre,0,A,2020-11-23 16:30:00
2020-10-16,102.519928,103.327024,101.568714,101.799310,1039400,-26,pre,0,A,2020-11-23 16:30:00
2020-10-19,101.357300,103.403859,101.117094,102.596763,636000,-25,pre,0,A,2020-11-23 16:30:00
2020-10-20,101.472618,102.750516,101.424574,101.741648,771000,-24,pre,0,A,2020-11-23 16:30:00
2020-10-21,100.723183,102.510316,100.040999,101.770477,894000,-23,pre,0,A,2020-11-23 16:30:00
2020-10-22,102.587173,102.894637,100.992209,101.193982,1064700,-22,pre,0,A,2020-11-23 16:30:00
2020-10-23,102.010689,103.173285,101.338115,103.029167,833900,-21,pre,0,A,2020-11-23 16:30:00
2020-10-26,100.531013,101.674396,99.685491,101.261242,1102000,-20,pre,0,A,2020-11-23 16:30:00
2020-10-27,101.885788,102.481502,100.992221,100.992221,1111400,-19,pre,0,A,2020-11-23 16:30:00
2020-10-28,97.677361,101.242016,97.600493,100.329229,1180800,-18,pre,0,A,2020-11-23 16:30:00
2020-10-29,98.023262,99.022520,96.822232,98.263468,1421900,-17,pre,0,A,2020-11-23 16:30:00
2020-10-30,98.090530,98.340347,96.706949,97.783067,2310000,-16,pre,0,A,2020-11-23 16:30:00
2020-11-02,101.117126,101.222818,99.243522,99.464508,1572300,-15,pre,0,A,2020-11-23 16:30:00
2020-11-03,102.836990,103.874682,101.981858,102.260497,1175000,-14,pre,0,A,2020-11-23 16:30:00
2020-11-04,104.239799,105.498484,103.038769,103.836255,1357300,-13,pre,0,A,2020-11-23 16:30:00
2020-11-05,106.017303,107.545017,105.373553,106.238296,1143100,-12,pre,0,A,2020-11-23 16:30:00
2020-11-06,108.131126,108.909391,106.007706,106.420861,1036600,-11,pre,0,A,2020-11-23 16:30:00
2020-11-09,108.092690,112.896809,107.986998,111.609309,2177900,-10,pre,0,A,2020-11-23 16:30:00
2020-11-10,105.882805,108.486644,104.720209,108.400166,2124800,-9,pre,0,A,2020-11-23 16:30:00
2020-11-11,105.123749,107.410507,104.576072,106.785970,1792800,-8,pre,0,A,2020-11-23 16:30:00
2020-11-12,105.152596,106.661089,104.633750,105.114162,1094300,-7,pre,0,A,2020-11-23 16:30:00
2020-11-13,105.853958,107.170289,105.479237,106.132598,1356800,-6,pre,0,A,2020-11-23 16:30:00
2020-11-16,105.950050,107.122257,105.181396,106.651455,1656100,-5,pre,0,A,2020-11-23 16:30:00
2020-11-17,105.556114,106.430460,104.970011,106.171041,1571500,-4,pre,0,A,2020-11-23 16:30:00
2020-11-18,101.799294,105.575332,101.587918,105.258266,2047900,-3,pre,0,A,2020-11-23 16:30:00
2020-11-19,104.422348,104.691378,101.069074,102.558347,1886400,-2,pre,0,A,2020-11-23 16:30:00
2020-11-20,106.545761,107.900526,104.076444,104.383907,2775400,-1,pre,0,A,2020-11-23 16:30:00
2020-11-23,107.814064,108.015836,105.267879,107.035799,3258700,0,pre,0,A,2020-11-23 16:30:00
2020-11-24,110.187294,114.299619,107.064616,114.299619,5559900,1,post,0,A,2020-11-23 16:30:00
2020-11-25,109.870216,112.377967,108.967047,111.542048,2862500,2,post,0,A,2020-11-23 16:30:00
2020-11-27,109.620415,110.475555,108.515473,109.312951,983700,3,post,0,A,2020-11-23 16:30:00
2020-11-30,112.320312,112.483651,109.216848,109.428231,3778400,4,post,0,A,2020-11-23 16:30:00
2020-12-01,110.840660,113.742345,110.533197,112.973691,1753700,5,post,0,A,2020-11-23 16:30:00
2020-12-02,110.081589,111.407523,109.658824,111.100060,1735800,6,post,0,A,2020-11-23 16:30:00
2020-12-03,109.130386,110.898299,108.726842,109.678056,1511400,7,post,0,A,2020-11-23 16:30:00

In [ ]:
df_market_events = pd.concat(market_events, ignore_index=False)

In [32]:
df_market_events.head()

Price,Close,High,Low,Open,Volume,relative_day,window,event_id,symbol,earnings_timestamp
Date,,,,,,,,,,
2020-10-13,101.290070,101.856960,100.848091,101.309290,915500,-29,pre,0,A,2020-11-23 16:30:00
2020-10-14,100.944153,102.491080,100.809638,101.357307,906700,-28,pre,0,A,2020-11-23 16:30:00
2020-10-15,101.193970,101.578301,99.810381,100.021763,723000,-27,pre,0,A,2020-11-23 16:30:00
2020-10-16,102.519928,103.327024,101.568714,101.799310,1039400,-26,pre,0,A,2020-11-23 16:30:00
2020-10-19,101.357300,103.403859,101.117094,102.596763,636000,-25,pre,0,A,2020-11-23 16:30:00

In [29]:
# clean the original earnings transcripts dataframe to only include valid events
valid_events = set(valid_events)
df_clean = df[df["event_id"].isin(valid_events)].copy()
print(df_clean.head())
df_clean.shape, df.shape

  symbol  quarter  year                date  \
0      A        4  2020 2020-11-23 16:30:00
1      A        3  2020 2020-08-18 16:30:00
2      A        2  2020 2020-05-21 16:30:00
3      A        1  2020 2020-02-18 16:30:00
4      A        4  2021 2021-11-22 16:30:00

                                             content  \
0  Operator: Good afternoon, and welcome to the A...
1  Operator: Good afternoon, and welcome to the A...
2  Operator: Good afternoon, and welcome to the A...
3  Operator: Good afternoon and welcome to the Ag...
4  Operator: Good afternoon and welcome to the Ag...

                                  structured_content  \
0  [{'speaker': 'Operator', 'text': "Good afterno...
1  [{'speaker': 'Operator', 'text': "Good afterno...
2  [{'speaker': 'Operator', 'text': "Good afterno...
3  [{'speaker': 'Operator', 'text': "Good afterno...
4  [{'speaker': 'Operator', 'text': "Good afterno...

                 company_name  company_id  event_id
0  Agilent Technologies, Inc.    154924.0         0
1  Agilent Technologies, Inc.    154924.0         1
2  Agilent Technologies, Inc.    154924.0         2
3  Agilent Technologies, Inc.    154924.0         3
4  Agilent Technologies, Inc.    154924.0         4

((29574, 9), (33362, 9))

In [30]:
df_clean.to_csv('earnings_transcripts_clean.csv', index=False)

In [33]:
df_market_events.to_csv('marketdata_to_events.csv', index=True)

In [34]:
# reduce the cleaned earnings transcripts dataframe to only the relevant columns
df_trscrpt = pd.read_csv('earnings_transcripts_clean.csv')
trscrpt_cols = ["event_id", "symbol", "date", "content"]
df_trscrpt_red = df_trscrpt[trscrpt_cols].copy()
df_trscrpt_red.head()

,event_id,symbol,date,content
0,0,A,2020-11-23 16:30:00,"Operator: Good afternoon, and welcome to the A..."
1,1,A,2020-08-18 16:30:00,"Operator: Good afternoon, and welcome to the A..."
2,2,A,2020-05-21 16:30:00,"Operator: Good afternoon, and welcome to the A..."
3,3,A,2020-02-18 16:30:00,Operator: Good afternoon and welcome to the Ag...
4,4,A,2021-11-22 16:30:00,Operator: Good afternoon and welcome to the Ag...

In [35]:
# sort earnings events chronologically
df_trscrpt_red = df_trscrpt_red.sort_values("date").reset_index(drop=True)
df_trscrpt_red.head()

,event_id,symbol,date,content
0,10404,AAPL,2005-10-13 14:45:00,TRANSCRIPT SPONSOR :\nApple's Q4 2005 Conferen...
1,32947,COP,2005-10-30 17:00:00,Operator: Ladies and gentlemen and welcome to ...
2,32026,GLW,2005-10-31 17:00:00,Operator: Good morning everyone. Welcome to t...
3,33031,XOM,2005-10-31 17:00:00,Operator: I would like to turn the call over t...
4,33161,XEL,2005-10-31 17:00:00,Operator: Good morning. My name is Dennis and...

In [36]:
df_trscrpt_red.to_csv('earnings_transcripts_sorted.csv', index=False)